version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      ./.env
    ports:
      - "80:${PORT}"
    restart: always
    depends_on:
      - postgres
    networks:
      - awesome
    volumes:
      - .:/var/www
      - /var/www/node_modules
  postgres:
    container_name: database
    image: postgres:12
    ports:
      - "5423:5432"
    env_file:
      ./.env
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - awesome

networks:
  awesome:
    driver: bridge