name: CI-CD
on:
  push:
    branches: [ feature/deploy ]

push_to_hub:
  runs-on: ubuntu-latest

  steps:
    - name: checkout repo
      uses: actions/checkout@v3

  - name: Login to DockerHub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push
    uses: docker/build-push-action@v2
    with:
      context: ./
      file: ./Dockerfile
      push: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest